// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsBD5ljdUzzQRYt_8iciG1fPMuamYFkhM',
    appId: '1:88767714428:android:0aeaadba582724f673a5f9',
    messagingSenderId: '88767714428',
    projectId: 'pokeapp-database',
    authDomain: 'pokeapp-database.firebaseapp.com',
    storageBucket: 'pokeapp-database.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID', // Puedes dejarlo así si no usas Analytics
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsBD5ljdUzzQRYt_8iciG1fPMuamYFkhM',
    appId: '1:88767714428:android:0aeaadba582724f673a5f9',
    messagingSenderId: '88767714428',
    projectId: 'pokeapp-database',
    storageBucket: 'pokeapp-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk4LGlY02lqRyA_21nAxvELytnweeX0oc',
    appId: '1:88767714428:ios:d5c6e8de20f603f973a5f9',
    messagingSenderId: '88767714428',
    projectId: 'pokeapp-database',
    storageBucket: 'pokeapp-database.firebasestorage.app',
    iosBundleId: 'com.example.ldsw36HttpPokeapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk4LGlY02lqRyA_21nAxvELytnweeX0oc',
    appId: '1:88767714428:ios:d5c6e8de20f603f973a5f9',
    messagingSenderId: '88767714428',
    projectId: 'pokeapp-database',
    storageBucket: 'pokeapp-database.firebasestorage.app',
    iosBundleId: 'com.example.ldsw36HttpPokeapi',
  );
}
